// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/fsdevblog/gophkeeper/internal/domain/models"
	dto "github.com/fsdevblog/gophkeeper/internal/storage/repos/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEntryRepository is a mock of EntryRepository interface.
type MockEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntryRepositoryMockRecorder
	isgomock struct{}
}

// MockEntryRepositoryMockRecorder is the mock recorder for MockEntryRepository.
type MockEntryRepositoryMockRecorder struct {
	mock *MockEntryRepository
}

// NewMockEntryRepository creates a new mock instance.
func NewMockEntryRepository(ctrl *gomock.Controller) *MockEntryRepository {
	mock := &MockEntryRepository{ctrl: ctrl}
	mock.recorder = &MockEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryRepository) EXPECT() *MockEntryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEntryRepository) Create(ctx context.Context, args dto.CreateEntryArgs) (*models.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, args)
	ret0, _ := ret[0].(*models.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEntryRepositoryMockRecorder) Create(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEntryRepository)(nil).Create), ctx, args)
}

// GetAllByUser mocks base method.
func (m *MockEntryRepository) GetAllByUser(ctx context.Context, userID uuid.UUID, limit, offset int32) ([]models.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]models.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByUser indicates an expected call of GetAllByUser.
func (mr *MockEntryRepositoryMockRecorder) GetAllByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByUser", reflect.TypeOf((*MockEntryRepository)(nil).GetAllByUser), ctx, userID, limit, offset)
}

// GetCountByUser mocks base method.
func (m *MockEntryRepository) GetCountByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountByUser", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountByUser indicates an expected call of GetCountByUser.
func (mr *MockEntryRepositoryMockRecorder) GetCountByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountByUser", reflect.TypeOf((*MockEntryRepository)(nil).GetCountByUser), ctx, userID)
}

// MockEntryFieldRepository is a mock of EntryFieldRepository interface.
type MockEntryFieldRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntryFieldRepositoryMockRecorder
	isgomock struct{}
}

// MockEntryFieldRepositoryMockRecorder is the mock recorder for MockEntryFieldRepository.
type MockEntryFieldRepositoryMockRecorder struct {
	mock *MockEntryFieldRepository
}

// NewMockEntryFieldRepository creates a new mock instance.
func NewMockEntryFieldRepository(ctrl *gomock.Controller) *MockEntryFieldRepository {
	mock := &MockEntryFieldRepository{ctrl: ctrl}
	mock.recorder = &MockEntryFieldRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryFieldRepository) EXPECT() *MockEntryFieldRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockEntryFieldRepository) BatchCreate(ctx context.Context, fields []dto.CreateEntryFieldArgs, resultRow func(int, *models.EntryField, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, fields, resultRow)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockEntryFieldRepositoryMockRecorder) BatchCreate(ctx, fields, resultRow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockEntryFieldRepository)(nil).BatchCreate), ctx, fields, resultRow)
}

// GetFieldsByEntryIDs mocks base method.
func (m *MockEntryFieldRepository) GetFieldsByEntryIDs(ctx context.Context, entryIDs []uuid.UUID) ([]models.EntryField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFieldsByEntryIDs", ctx, entryIDs)
	ret0, _ := ret[0].([]models.EntryField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFieldsByEntryIDs indicates an expected call of GetFieldsByEntryIDs.
func (mr *MockEntryFieldRepositoryMockRecorder) GetFieldsByEntryIDs(ctx, entryIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFieldsByEntryIDs", reflect.TypeOf((*MockEntryFieldRepository)(nil).GetFieldsByEntryIDs), ctx, entryIDs)
}

// GetUserFieldsByEntryID mocks base method.
func (m *MockEntryFieldRepository) GetUserFieldsByEntryID(ctx context.Context, entryID, userID uuid.UUID) ([]models.EntryField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFieldsByEntryID", ctx, entryID, userID)
	ret0, _ := ret[0].([]models.EntryField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFieldsByEntryID indicates an expected call of GetUserFieldsByEntryID.
func (mr *MockEntryFieldRepositoryMockRecorder) GetUserFieldsByEntryID(ctx, entryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFieldsByEntryID", reflect.TypeOf((*MockEntryFieldRepository)(nil).GetUserFieldsByEntryID), ctx, entryID, userID)
}
