// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/fsdevblog/gophkeeper/internal/domain/models"
	dto "github.com/fsdevblog/gophkeeper/internal/storage/repos/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEntryRepository is a mock of EntryRepository interface.
type MockEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntryRepositoryMockRecorder
	isgomock struct{}
}

// MockEntryRepositoryMockRecorder is the mock recorder for MockEntryRepository.
type MockEntryRepositoryMockRecorder struct {
	mock *MockEntryRepository
}

// NewMockEntryRepository creates a new mock instance.
func NewMockEntryRepository(ctrl *gomock.Controller) *MockEntryRepository {
	mock := &MockEntryRepository{ctrl: ctrl}
	mock.recorder = &MockEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryRepository) EXPECT() *MockEntryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEntryRepository) Create(ctx context.Context, args dto.CreateEntryArgs) (*models.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, args)
	ret0, _ := ret[0].(*models.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEntryRepositoryMockRecorder) Create(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEntryRepository)(nil).Create), ctx, args)
}

// MockEntryFieldRepository is a mock of EntryFieldRepository interface.
type MockEntryFieldRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntryFieldRepositoryMockRecorder
	isgomock struct{}
}

// MockEntryFieldRepositoryMockRecorder is the mock recorder for MockEntryFieldRepository.
type MockEntryFieldRepositoryMockRecorder struct {
	mock *MockEntryFieldRepository
}

// NewMockEntryFieldRepository creates a new mock instance.
func NewMockEntryFieldRepository(ctrl *gomock.Controller) *MockEntryFieldRepository {
	mock := &MockEntryFieldRepository{ctrl: ctrl}
	mock.recorder = &MockEntryFieldRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryFieldRepository) EXPECT() *MockEntryFieldRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockEntryFieldRepository) BatchCreate(ctx context.Context, entryID uuid.UUID, fields []dto.CreateEntryFieldArgs, resultRow func(int, *models.EntryField, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, entryID, fields, resultRow)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockEntryFieldRepositoryMockRecorder) BatchCreate(ctx, entryID, fields, resultRow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockEntryFieldRepository)(nil).BatchCreate), ctx, entryID, fields, resultRow)
}
