// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package sqlcgen

import (
	"context"
	"errors"

	"github.com/fsdevblog/gophkeeper/internal/domain/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const entryFields_BatchCreate = `-- name: EntryFields_BatchCreate :batchone
INSERT INTO entry_fields
    (entry_id, key, value, is_private)
VALUES
    ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, entry_id, key, value, is_private
`

type EntryFields_BatchCreateBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type EntryFields_BatchCreateParams struct {
	EntryID   uuid.UUID
	Key       models.EntryFieldKeyType
	Value     []byte
	IsPrivate bool
}

func (q *Queries) EntryFields_BatchCreate(ctx context.Context, arg []EntryFields_BatchCreateParams) *EntryFields_BatchCreateBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.EntryID,
			a.Key,
			a.Value,
			a.IsPrivate,
		}
		batch.Queue(entryFields_BatchCreate, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &EntryFields_BatchCreateBatchResults{br, len(arg), false}
}

func (b *EntryFields_BatchCreateBatchResults) QueryRow(f func(int, EntryField, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i EntryField
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryID,
			&i.Key,
			&i.Value,
			&i.IsPrivate,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *EntryFields_BatchCreateBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
