// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package sqlcgen

import (
	"context"

	"github.com/fsdevblog/gophkeeper/internal/domain/models"
	"github.com/google/uuid"
)

const devices_Create = `-- name: Devices_Create :one
INSERT INTO devices
    (type, user_id, client_uuid, platform, platform_version, state_version, app_version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, client_uuid)
    DO UPDATE SET
                  updated_at = NOW(),
                  last_active_at = NOW()
RETURNING id, created_at, updated_at, type, user_id, client_uuid, platform, platform_version, state_version, app_version, last_active_at
`

type Devices_CreateParams struct {
	Type            models.DeviceType
	UserID          uuid.UUID
	ClientUuid      uuid.UUID
	Platform        string
	PlatformVersion string
	StateVersion    uuid.UUID
	AppVersion      string
}

func (q *Queries) Devices_Create(ctx context.Context, arg Devices_CreateParams) (Device, error) {
	row := q.db.QueryRow(ctx, devices_Create,
		arg.Type,
		arg.UserID,
		arg.ClientUuid,
		arg.Platform,
		arg.PlatformVersion,
		arg.StateVersion,
		arg.AppVersion,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.UserID,
		&i.ClientUuid,
		&i.Platform,
		&i.PlatformVersion,
		&i.StateVersion,
		&i.AppVersion,
		&i.LastActiveAt,
	)
	return i, err
}
