// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entry_fields.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const entryFields_GetFieldsByEntryIDs = `-- name: EntryFields_GetFieldsByEntryIDs :many
SELECT id, created_at, updated_at, entry_id, key, value, is_private FROM entry_fields WHERE entry_id = ANY($1::uuid[])
`

func (q *Queries) EntryFields_GetFieldsByEntryIDs(ctx context.Context, ids []uuid.UUID) ([]EntryField, error) {
	rows, err := q.db.Query(ctx, entryFields_GetFieldsByEntryIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryField
	for rows.Next() {
		var i EntryField
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryID,
			&i.Key,
			&i.Value,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
