// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package sqlcgen

import (
	"context"

	"github.com/fsdevblog/gophkeeper/internal/domain/models"
	"github.com/google/uuid"
)

const entries_Create = `-- name: Entries_Create :one
INSERT INTO entries
    (type, user_id, device_id, title)
    VALUES
    ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, type, user_id, device_id, title
`

type Entries_CreateParams struct {
	Type     models.EntryType
	UserID   uuid.UUID
	DeviceID uuid.UUID
	Title    string
}

func (q *Queries) Entries_Create(ctx context.Context, arg Entries_CreateParams) (Entry, error) {
	row := q.db.QueryRow(ctx, entries_Create,
		arg.Type,
		arg.UserID,
		arg.DeviceID,
		arg.Title,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.UserID,
		&i.DeviceID,
		&i.Title,
	)
	return i, err
}

const entries_GetAllByUserID = `-- name: Entries_GetAllByUserID :many
SELECT id, created_at, updated_at, type, user_id, device_id, title FROM entries WHERE user_id = $1 OFFSET $2 LIMIT $3
`

type Entries_GetAllByUserIDParams struct {
	UserID uuid.UUID
	Offset int32
	Limit  int32
}

func (q *Queries) Entries_GetAllByUserID(ctx context.Context, arg Entries_GetAllByUserIDParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, entries_GetAllByUserID, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.UserID,
			&i.DeviceID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entries_GetCountByUserID = `-- name: Entries_GetCountByUserID :one
SELECT count(*) FROM entries WHERE user_id = $1
`

func (q *Queries) Entries_GetCountByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, entries_GetCountByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
