// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/fsdevblog/gophkeeper/internal/domain/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID              uuid.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Type            models.DeviceType
	UserID          uuid.UUID
	ClientUuid      uuid.UUID
	Platform        string
	PlatformVersion string
	StateVersion    uuid.UUID
	AppVersion      string
	LastActiveAt    pgtype.Timestamptz
}

type Entry struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Type      models.EntryType
	UserID    uuid.UUID
	DeviceID  uuid.UUID
	Title     string
}

type EntryField struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	EntryID   uuid.UUID
	Key       models.EntryFieldKeyType
	Value     []byte
	IsPrivate bool
}

type User struct {
	ID                uuid.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Username          string
	EncryptedPassword string
}
