// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/fsdevblog/gophkeeper/internal/domain/models"
	pag "github.com/fsdevblog/gophkeeper/internal/pag"
	svcauth "github.com/fsdevblog/gophkeeper/internal/storage/services/svcauth"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthProvider is a mock of AuthProvider interface.
type MockAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAuthProviderMockRecorder
	isgomock struct{}
}

// MockAuthProviderMockRecorder is the mock recorder for MockAuthProvider.
type MockAuthProviderMockRecorder struct {
	mock *MockAuthProvider
}

// NewMockAuthProvider creates a new mock instance.
func NewMockAuthProvider(ctrl *gomock.Controller) *MockAuthProvider {
	mock := &MockAuthProvider{ctrl: ctrl}
	mock.recorder = &MockAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthProvider) EXPECT() *MockAuthProviderMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuthProvider) Authenticate(ctx context.Context, args svcauth.AuthenticateArgs) (string, *models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, args)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*models.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthProviderMockRecorder) Authenticate(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthProvider)(nil).Authenticate), ctx, args)
}

// Register mocks base method.
func (m *MockAuthProvider) Register(ctx context.Context, args svcauth.RegisterArgs) (string, *models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, args)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*models.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Register indicates an expected call of Register.
func (mr *MockAuthProviderMockRecorder) Register(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthProvider)(nil).Register), ctx, args)
}

// MockEntryProvider is a mock of EntryProvider interface.
type MockEntryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockEntryProviderMockRecorder
	isgomock struct{}
}

// MockEntryProviderMockRecorder is the mock recorder for MockEntryProvider.
type MockEntryProviderMockRecorder struct {
	mock *MockEntryProvider
}

// NewMockEntryProvider creates a new mock instance.
func NewMockEntryProvider(ctrl *gomock.Controller) *MockEntryProvider {
	mock := &MockEntryProvider{ctrl: ctrl}
	mock.recorder = &MockEntryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryProvider) EXPECT() *MockEntryProviderMockRecorder {
	return m.recorder
}

// GetSafeEntryFields mocks base method.
func (m *MockEntryProvider) GetSafeEntryFields(ctx context.Context, userID, entryID uuid.UUID) ([]models.EntryField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSafeEntryFields", ctx, userID, entryID)
	ret0, _ := ret[0].([]models.EntryField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSafeEntryFields indicates an expected call of GetSafeEntryFields.
func (mr *MockEntryProviderMockRecorder) GetSafeEntryFields(ctx, userID, entryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSafeEntryFields", reflect.TypeOf((*MockEntryProvider)(nil).GetSafeEntryFields), ctx, userID, entryID)
}

// GetUserEntries mocks base method.
func (m *MockEntryProvider) GetUserEntries(ctx context.Context, userID uuid.UUID, p *pag.Pagination) ([]models.Entry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEntries", ctx, userID, p)
	ret0, _ := ret[0].([]models.Entry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserEntries indicates an expected call of GetUserEntries.
func (mr *MockEntryProviderMockRecorder) GetUserEntries(ctx, userID, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEntries", reflect.TypeOf((*MockEntryProvider)(nil).GetUserEntries), ctx, userID, p)
}
